### ISSUE TITLE
[FEAT] 공통 스타일

### ISSUE THREAD

**Issue by Ahhhhhhyeong** [goorm-team-study-cc/carrot-clone#9]
**기능 요약**
프로젝트 내에서 공통으로 사용될 색상, 폰트 설정

**기능 설명**
색상만 나타낸 css
```css
:root{
  --main-color: #ff6600;
/* gray 색상 500을 기준으로 밝기순으로 나타냄 (gpt사용)*/
  --gray-100: #f3f4f6;
  --gray-200: #e5e7eb;
  --gray-300: #d1d5db;
  --gray-400: #aeb2b9;
  --gray-500: #868b94; /* 기준 색상 */
  --gray-600: #6b707a;
  --gray-700: #50545c;
  --gray-800: #36393f;
  --gray-900: #1f2124;
/* 공통적으로 사용될 폰트 추가(기존 index.css의 font-family써도 무방한가요?) */
}
```

**위치**
index.css

**기타(선택)**
